blueprint:
  name: Styrbar Remote Control for 3 Light Groups
  description: >
    Provides integration and control for the IKEA E2001/E2002 Styrbar remote control.
    Allows for turning lights on/off, adjusting brightness, and changing color temperature.
    Designed for a Zigbee2MQTT group of light bulbs.
    Added incremental color temperature adjustment.
  domain: automation
  input:
    middle_button_light:
      name: Light Entity For Middle Button
      description: The light to control.
      default:
      selector:
        entity:
          domain: light
    left_button_light:
      name: Light Entity For Left Button
      description: The light to control.
      default:
      selector:
        entity:
          domain: light
    right_button_light:
      name: Light Entity For Right Button
      description: The light to control.
      default:
      selector:
        entity:
          domain: light
    remote_controller:
      name: Styrbar Remote Control
      description: The IKEA E2001/E2002 remote control.
      selector:
        device: {}
    brightness_step:
      name: Brightness Step
      description: "Brightness adjustment step (slider percentage, 1-100%)."
      default: 5
      selector:
        number:
          min: 1
          max: 100
          step: 1
          unit_of_measurement: "%"
    delay_ms:
      name: Delay (ms) Between Steps
      description: "Delay in milliseconds between brightness adjustment steps."
      default: 300
      selector:
        number:
          min: 100
          max: 2000
          step: 100
          unit_of_measurement: "ms"
    transition_seconds:
      name: Transition Time (Seconds)
      description: "The duration in seconds for the light transition effect."
      default: 1
      selector:
        number:
          min: 0.1
          max: 9999
          step: 0.1
          unit_of_measurement: "s"
    transitiontime_for_onoff:
      name: Transition Time (Seconds)
      description: "The duration in seconds for the light transition effect when it turns on or off."
      default: 3
      selector:
        number:
          min: 1
          max: 5
          step: 0.5
          unit_of_measurement: "s"

trigger:
  - platform: device
    device_id: !input remote_controller
    domain: mqtt
    type: action
    subtype: "on"
    id: middle_light_on
  - platform: device
    device_id: !input remote_controller
    domain: mqtt
    type: action
    subtype: "off"
    id: middle_light_off
  - platform: device
    device_id: !input remote_controller
    domain: mqtt
    type: action
    subtype: arrow_left_click
    id: left_light_toggle
  - platform: device
    device_id: !input remote_controller
    domain: mqtt
    type: action
    subtype: arrow_left_hold
    id: change_color_left_hold
  - platform: device
    device_id: !input remote_controller
    domain: mqtt
    type: action
    subtype: arrow_left_release
    id: change_color_left_release
  - platform: device
    device_id: !input remote_controller
    domain: mqtt
    type: action
    subtype: arrow_right_click
    id: right_light_toggle
  - platform: device
    device_id: !input remote_controller
    domain: mqtt
    type: action
    subtype: arrow_right_hold
    id: change_color_right_hold
  - platform: device
    device_id: !input remote_controller
    domain: mqtt
    type: action
    subtype: arrow_right_release
    id: change_color_right_release
  - platform: device
    device_id: !input remote_controller
    domain: mqtt
    type: action
    subtype: brightness_move_down
    id: dim_down
  - platform: device
    device_id: !input remote_controller
    domain: mqtt
    type: action
    subtype: brightness_move_up
    id: dim_up
  - platform: device
    device_id: !input remote_controller
    domain: mqtt
    type: action
    subtype: brightness_stop
    id: dim_stop

variables:
  middle_button_light: !input middle_button_light
  left_button_light: !input left_button_light
  right_button_light: !input right_button_light
  transitiontime_for_onoff: !input transitiontime_for_onoff
  brightness_step: !input brightness_step

action:
  - choose:
      - conditions:
          - condition: trigger
            id: middle_light_on
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input middle_button_light
            data:
              transition: !input transitiontime_for_onoff
              
      - conditions:
          - condition: trigger
            id: middle_light_off
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input middle_button_light
            data:
              transition: !input transitiontime_for_onoff

      - conditions:
          - condition: trigger
            id: left_light_toggle
        sequence:
          - service: light.toggle
            target:
              entity_id: !input left_button_light
            data:
              transition: !input transitiontime_for_onoff
      - conditions:
          - condition: trigger
            id: right_light_toggle
        sequence:
          - service: light.toggle
            target:
              entity_id: !input right_button_light
            data:
              transition: !input transitiontime_for_onoff

      - conditions:
          - condition: trigger
            id: dim_down
        sequence:
          - repeat:
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input middle_button_light
                  data:
                    brightness_step_pct: "-{{ brightness_step | int(5) }}"
                    transition: !input transition_seconds
                - delay:
                    milliseconds: !input delay_ms
              until:
                - condition: trigger
                  id: dim_stop
      - conditions:
          - condition: trigger
            id: dim_up
        sequence:
          - repeat:
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input middle_button_light
                  data:
                    brightness_step_pct: "{{ brightness_step | int(5) }}"
                    transition: !input transition_seconds
                - delay:
                    milliseconds: !input delay_ms
              until:
                - condition: trigger
                  id: dim_stop
      - conditions:
          - condition: trigger
            id: change_color_left_hold
        sequence:
          - repeat:
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input middle_button_light
                  data:
                    color_temp_kelvin: "{{ state_attr(middle_button_light, 'color_temp_kelvin') - 100 }}"
                  delay:
                    milliseconds: !input delay_ms
              until:
                - condition: trigger
                  id: change_color_left_release
      - conditions:
          - condition: trigger
            id: change_color_right_hold
        sequence:
          - repeat:
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input middle_button_light
                  data:
                    color_temp_kelvin: "{{ state_attr(middle_button_light, 'color_temp_kelvin') + 100 }}"
                  delay:
                    milliseconds: !input delay_ms
              until:
                - condition: trigger
                  id: change_color_right_release
mode: restart
